# Generated by Django 3.2 on 2021-05-08 09:15

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Author',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='ФИО автора')),
                ('books_amount', models.IntegerField(default=0, editable=False, verbose_name='Количество книг автора')),
                ('desc', models.TextField(blank=True, verbose_name='Описание автора')),
                ('status', models.BooleanField(default=True, verbose_name='Статус')),
                ('slug', models.SlugField(blank=True, unique=True)),
                ('image', models.ImageField(upload_to='', verbose_name='Изображение')),
            ],
            options={
                'verbose_name': 'Автор',
                'verbose_name_plural': 'Авторы',
            },
        ),
        migrations.CreateModel(
            name='Basket',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.IntegerField(choices=[(1, 'In Process'), (2, 'Abandoned'), (3, 'Closed'), (4, 'On Hands'), (5, 'Expired')], verbose_name='Статус')),
                ('return_date', models.DateTimeField(blank=True, null=True, verbose_name='Дата и время возврата')),
                ('date_of_taking', models.DateTimeField(blank=True, null=True, verbose_name='Дата и время взятия')),
            ],
            options={
                'verbose_name': 'Корзина',
                'verbose_name_plural': 'Корзины',
            },
        ),
        migrations.CreateModel(
            name='ClientGroup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='Название')),
                ('discount', models.IntegerField(default=0, verbose_name='Скидка в процентах')),
                ('clients_amount', models.IntegerField(default=0, editable=False, verbose_name='Количество клиентов')),
                ('show_prices', models.BooleanField(default=False, verbose_name='Показывать ли цены')),
                ('status', models.BooleanField(default=True, verbose_name='Статус')),
            ],
            options={
                'verbose_name': 'Группа клиентов',
                'verbose_name_plural': 'Группы клиентов',
            },
        ),
        migrations.CreateModel(
            name='Genre',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='Название жанра')),
                ('books_amount', models.IntegerField(default=0, editable=False, verbose_name='Количество книг жанра')),
                ('desc', models.TextField(blank=True, verbose_name='Описание жанра')),
                ('status', models.BooleanField(default=True, verbose_name='Статус')),
                ('slug', models.SlugField(blank=True, unique=True)),
            ],
            options={
                'verbose_name': 'Жанр',
                'verbose_name_plural': 'Жанры',
            },
        ),
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_of_birth', models.DateField(blank=True, null=True, verbose_name='Дата рождения')),
                ('address', models.CharField(max_length=255, verbose_name='Адрес')),
                ('mobile_phone', models.CharField(max_length=28, unique=True, verbose_name='Мобильный номер')),
                ('home_phone', models.CharField(blank=True, max_length=28, null=True, unique=True, verbose_name='Домашний номер')),
                ('baskets', models.ManyToManyField(to='mainapp.Basket', verbose_name='Корзины клиента')),
                ('group', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='mainapp.clientgroup', verbose_name='Группа')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='user')),
            ],
            options={
                'verbose_name': 'Клиент',
                'verbose_name_plural': 'Клиенты',
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='Заголовок книги')),
                ('collateral_price', models.DecimalField(blank=True, decimal_places=2, max_digits=9, verbose_name='Залоговая стоимость')),
                ('rental_price', models.DecimalField(decimal_places=2, max_digits=9, verbose_name='Стоимость проката')),
                ('amount', models.IntegerField(blank=True, default=0, verbose_name='Количество')),
                ('desc', models.TextField(blank=True, verbose_name='Описание книги')),
                ('status', models.BooleanField(default=True, verbose_name='Статус')),
                ('slug', models.SlugField(blank=True, unique=True)),
                ('image', models.ImageField(upload_to='', verbose_name='Изображение')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainapp.author', verbose_name='Автор')),
                ('genre', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainapp.genre', verbose_name='Жанр')),
            ],
            options={
                'verbose_name': 'Книга',
                'verbose_name_plural': 'Книги',
            },
        ),
        migrations.AddField(
            model_name='basket',
            name='books',
            field=models.ManyToManyField(blank=True, to='mainapp.Book', verbose_name='Книги в корзине'),
        ),
    ]
