# Generated by Django 3.2 on 2021-04-10 15:48

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Author',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='ФИО автора')),
                ('books_amount', models.IntegerField(verbose_name='Количество книг автора')),
                ('desc', models.TextField(null=True, verbose_name='Описание автора')),
                ('status', models.BooleanField(default=True, verbose_name='Статус')),
                ('slug', models.SlugField(unique=True)),
                ('image', models.ImageField(upload_to='', verbose_name='Изображение')),
            ],
        ),
        migrations.CreateModel(
            name='ClientGroup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Название')),
                ('discount', models.IntegerField(verbose_name='Скидка')),
                ('clients_amount', models.IntegerField(verbose_name='Количество клиентов')),
                ('show_prices', models.BooleanField(default=True, verbose_name='Показывать ли цены')),
                ('status', models.BooleanField(default=True, verbose_name='Статус')),
            ],
        ),
        migrations.CreateModel(
            name='Genre',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Название жанра')),
                ('books_amount', models.IntegerField(verbose_name='Количество книг жанра')),
                ('desc', models.TextField(null=True, verbose_name='Описание жанра')),
                ('status', models.BooleanField(default=True, verbose_name='Статус')),
                ('slug', models.SlugField(unique=True)),
                ('image', models.ImageField(upload_to='', verbose_name='Изображение')),
            ],
        ),
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Заголовок книги')),
                ('collateral_price', models.DecimalField(decimal_places=2, max_digits=9, verbose_name='Залоговая стоимость')),
                ('rental_price', models.DecimalField(decimal_places=2, max_digits=9, verbose_name='Стоимость проката')),
                ('amount', models.IntegerField(verbose_name='Количество книг')),
                ('desc', models.TextField(null=True, verbose_name='Описание книги')),
                ('status', models.BooleanField(default=True, verbose_name='Статус')),
                ('slug', models.SlugField(unique=True)),
                ('image', models.ImageField(upload_to='')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainapp.author', verbose_name='Автор')),
                ('genre', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainapp.genre', verbose_name='Жанр')),
            ],
        ),
        migrations.CreateModel(
            name='Basket',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.IntegerField(choices=[(1, 'In Process'), (2, 'Abandoned'), (3, 'Closed'), (4, 'On Hands'), (5, 'Expired')], verbose_name='Статус')),
                ('return_date', models.DateTimeField(verbose_name='Дата и время возврата')),
                ('date_of_taking', models.DateTimeField(verbose_name='Дата и время взятия')),
                ('books', models.ManyToManyField(blank=True, to='mainapp.Book', verbose_name='Книги в корзине')),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Клиент')),
            ],
        ),
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_of_birth', models.DateField(blank=True, null=True, verbose_name='Дата рождения')),
                ('address', models.CharField(max_length=255, verbose_name='Адрес')),
                ('mobile_phone', models.CharField(max_length=28, unique=True, verbose_name='Мобильный номер')),
                ('home_phone', models.CharField(blank=True, max_length=28, null=True, unique=True, verbose_name='Домашний номер')),
                ('group', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='mainapp.clientgroup', verbose_name='Группа')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Клиент')),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'abstract': False,
                'swappable': 'mainapp.models.Client',
            },
        ),
    ]
