# Generated by Django 3.2 on 2021-04-08 10:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='register_datetime',
            field=models.DateTimeField(null=True, verbose_name='Дата и время регистрации'),
        ),
    ]
