# Generated by Django 3.2 on 2021-04-08 16:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0002_client_register_datetime'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='status',
            field=models.BooleanField(default=False, verbose_name='Статус'),
        ),
    ]
