# Generated by Django 3.2 on 2021-05-09 11:56

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0002_alter_clientgroup_discount'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clientgroup',
            name='discount',
            field=models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(-100), django.core.validators.MaxValueValidator(100)], verbose_name='Скидка в процентах'),
        ),
        migrations.AlterField(
            model_name='clientgroup',
            name='status',
            field=models.BooleanField(default=True, editable=False, verbose_name='Статус'),
        ),
    ]
