# Generated by Django 3.2 on 2021-05-22 16:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0004_sliderimages'),
    ]

    operations = [
        migrations.AddField(
            model_name='sliderimages',
            name='status',
            field=models.BooleanField(default=True, verbose_name='Статус'),
        ),
    ]
