# Generated by Django 3.2 on 2021-04-28 16:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0006_auto_20210411_1050'),
    ]

    operations = [
        migrations.AlterField(
            model_name='author',
            name='books_amount',
            field=models.IntegerField(editable=False, verbose_name='Количество книг автора'),
        ),
        migrations.AlterField(
            model_name='author',
            name='desc',
            field=models.TextField(blank=True, verbose_name='Описание автора'),
        ),
        migrations.AlterField(
            model_name='book',
            name='desc',
            field=models.TextField(blank=True, verbose_name='Описание книги'),
        ),
        migrations.AlterField(
            model_name='genre',
            name='books_amount',
            field=models.IntegerField(editable=False, verbose_name='Количество книг жанра'),
        ),
        migrations.AlterField(
            model_name='genre',
            name='desc',
            field=models.TextField(blank=True, verbose_name='Описание жанра'),
        ),
    ]
