# Generated by Django 3.2 on 2021-04-09 09:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0007_alter_client_password'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='client',
            name='last_visit',
        ),
        migrations.AlterField(
            model_name='client',
            name='last_login',
            field=models.DateTimeField(null=True, verbose_name='Дата и время последнего входа'),
        ),
    ]
