# Generated by Django 3.2 on 2021-04-09 10:09

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0008_auto_20210409_1248'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='register_datetime',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Дата и время регистрации'),
        ),
    ]
