# Generated by Django 3.2 on 2021-04-28 16:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0008_auto_20210428_1936'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='genre',
            name='image',
        ),
        migrations.AlterField(
            model_name='book',
            name='image',
            field=models.ImageField(upload_to='', verbose_name='Изображение'),
        ),
    ]
