# Generated by Django 3.2 on 2021-04-09 10:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0010_client_username'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='client',
            name='username',
        ),
    ]
