# Generated by Django 3.2 on 2021-04-09 12:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0012_rename_email_client_username'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='email',
            field=models.EmailField(default=None, max_length=150, unique=True, verbose_name='Адрес E-mail'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='client',
            name='username',
            field=models.CharField(blank=True, max_length=150),
        ),
    ]
