# Generated by Django 3.2 on 2021-04-10 14:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0019_client_username'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='client',
            options={'verbose_name': 'user', 'verbose_name_plural': 'users'},
        ),
    ]
